####################################################################
#
# These are development settings for the project. To deploy the
# project to production you will need to write another file for
# `docker stack deploy`
#
####################################################################

version: '3.5'

services:
  events-service:
    build:
      dockerfile: Dockerfile-test
      context: ./events-service/
    container_name: events
#    image: golang:1.10.3
    restart: always
    volumes:
      - "./events-service/src/:/src"
    ports:
      - "80:8080"
    networks:
      - frontend-tier
      - events-data-tier
    environment:
      - LOG=DEBUG
      - MONGO=mongodb://events-db:27017
    command: 'ping 127.0.0.1'

  events-db: # Don't use volume for db, then no need to tear down
    image: mongo:3.3
    container_name: events-db
    ports:
      - "27017:27017"
    networks:
      - events-data-tier

#volumes:
#  events-src:

networks:
  frontend-tier:
    driver: bridge
  events-data-tier:
    driver: bridge

