####################################################################
#
# These are development settings for the project. To deploy the
# project to production you will need to write another file for
# `docker stack deploy`
#
####################################################################

version: '3.5'

services:
  party-service:
    restart: always
    build: ./party-service/
    container_name: party-service
    ports:
      - "80:8080"
    networks:
      - frontend-tier
      - party-data-tier
      - event-log-tier
    environment:
      - PORT=8080
      - MONGO=mongodb://party-db:27017
      - KAFKA_BROKERS=127.0.0.1:9092
    depends_on:
      - kafka
    command: './app'

  party-db:
    image: mongo:3.3
    container_name: party-db
    ports:
      - "27017:27017"
    volumes:
       - db-data:/data/db
    networks:
      - party-data-tier

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: /Users/eriksterneberg/workspace/kafka-demo2/kafka-docker/
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - event-log-tier

volumes:
  db-data:

networks:
  frontend-tier:
    driver: bridge
  party-data-tier:
    driver: bridge
  event-log-tier:
    driver: bridge

