####################################################################
#
# These are development settings for the project. To deploy the
# project to production you will need to write another file for
# `docker stack deploy`
#
####################################################################

version: '3.5'

services:
  party-service:
    build:
      dockerfile: Dockerfile.test
      context: ./party-service/
    container_name: party
    restart: always
    volumes:
#      - "/Users/eriksterneberg/workspace/go/src/github.com/eriksterneberg/go-demo-app/party-service/src:/go/src/github.com/eriksterneberg/go-demo-app/party-service/src"
      - "./party-service/src:/go/src/github.com/eriksterneberg/go-demo-app/party-service/src"
      - "./party-service/src/:/src"
    ports:
      - "80:8080"
    networks:
      - frontend-tier
      - party-data-tier
    environment:
      - PORT=8080
      - MONGO=mongodb://party-db:27017
      - KAFKA_BROKERS=kafka:9092

  party-db: # Don't use volume for db, then no need to tear down
    image: mongo:3.3
    container_name: party-db
    ports:
      - "27017:27017"
    networks:
      - party-data-tier

networks:
  frontend-tier:
    driver: bridge
  party-data-tier:
    driver: bridge

