####################################################################
#
# These are development settings for the project. To deploy the
# project to production you will need to write another file for
# `docker stack deploy`
#
####################################################################

version: '3.5'

services:
  party-service:
    restart: always
    build: ./party-service/
    ports:
      - "80:8080"
    networks:
      - frontend-tier
      - party-data-tier
    environment:
      - PORT=8080
      - MONGO=mongodb://party-db:27017
      - KAFKA_BROKERS=kafka:9092
    command: './app'

  party-db:
    image: mongo:3.3
    container_name: party-db
    ports:
      - "27017:27017"
    volumes:
       - db-data:/data/db
    networks:
      - party-data-tier

  # Need to add Kafka here

volumes:
  db-data:

networks:
  frontend-tier:
    driver: bridge
  party-data-tier:
    driver: bridge

